---
# tasks file for roles/rollback-svc
#################################################
# 방화벽 포트 제거
# 서비스 종료
# 서비스 설정 삭제
# 패키지 삭제
#################################################
- name: 방화벽 포트 제거
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
  loop: "{{ fw_svcs }}"
  ignore_errors: true

- name: 서비스 종료
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ svcs }}"

- name: 서비스 설정 삭제
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files }}"

- name: 패키지 삭제
  ansible.builtin.dnf:
    name: "{{ pkgs }}"
    state: absent